### ISSUE TITLE
CLI arguments for phantomjs

### ISSUE THREAD

**Issue by alexschwarz89** [Dachande663/PHP-PhantomJS#1]
I had the issue, that I could not parse the response because I got error messages like
"Unsafe JavaScript attempt to access frame with URL" from some Google Analytics.

Passing "--web-security=false" as an argument for phantomjs solves the problem. 

Maybe the class should support adding options.

**Comment by Dachande663** [comment]
Named options were intentionally left out to help forwards-compatability. Arguments can be passed through verbatim with the execute method.
